services:
  accounts:
    image: "sonalithorat/accounts:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sonali
  loans:
    image: "sonalithorat/loan:s2"
    container_name: loan-ms
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sonali
  cards:
    image: "sonalithorat/cards:s2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - sonali
networks:
  sonali:
    driver: "bridge"