server:
  port: 8081
  
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true 
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication 
          
          
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
          
#this property is required to create table automatically using entities
    defer-datasource-initialization: true
  
  profiles:
    active: "prod"
  
  config:
   import: "optional:configserver:http://localhost:8071/"
   
logging:
  level:
    com:
      sonali:
        accounts: debug
        
        orm:
          jdbc:
            bind: trace     

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j:
  retry:
    instances:
      getBuildInfo:
        max-attempts: 3
        wait-duration: 5s

      
management:
 endpoints:
  web: 
   exposure:
    include: "*"
 health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
 endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
 
 info:
  env:
   enabled: true

endpoints:
 shutdown:
  enabled: true
  
info:
  app:
    name: "accounts"
    description: "Accounts Application"
    version: "1.0.0"
eureka:
  instance:
   preferIpAddress: true
    
    
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka             